FROM node:12.22.1-alpine
WORKDIR /app
RUN apk add --no-cache \
   libpng-dev\
   autoconf\
   automake\
   libtool\
   make\
   gcc\
   musl-dev\
   nasm\
 && rm -rf /tmp/*
# COPY the package.json file, update any deps and install them
COPY package.json .
RUN yarn install

# copy the whole source folder(the dir is relative to the Dockerfile
COPY . .
CMD [ "yarn", "run", "develop" ]
